version: "3.8"
services:
  nodejs:
    container_name: hello-world
    image: helloworld
    build: 
      context: .
      dockerfile: dockerfile
    ports:
      - 3000:3000
    
volumes:
  nodejs: {}